---
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    groups:
      dev-dependencies:
        dependency-type: "development"
      minor-and-patch-py:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "19:00"
      timezone: "America/Chicago"
    labels:
      - "dependencies"
      - "dev"
      - "python"

  - package-ecosystem: "gomod"
    directory: "/"
    groups:
      minor-and-patch-go:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
    schedule:
      interval: "daily"
      time: "19:00"
      timezone: "America/Chicago"
    labels:
      - "dependencies"
      - "go"

  - package-ecosystem: "npm"
    directory: "/"
    groups:
      dev-dependencies:
        dependency-type: "development"
      minor-and-patch-npm:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "19:00"
      timezone: "America/Chicago"
    labels:
      - "dependencies"
      - "dev"
      - "javascript"

  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      dev-dependencies:
        dependency-type: "development"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "19:00"
      timezone: "America/Chicago"
    labels:
      - "dependencies"
      - "dev"
      - "github_actions"

  - package-ecosystem: "docker"
    directory: "/"
    groups:
      dev-dependencies:
        dependency-type: "development"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "19:00"
      timezone: "America/Chicago"
    labels:
      - "dependencies"
      - "dev"
      - "docker"
