name: Go - Test

on:
  pull_request:
    branches:
      - "main"
    paths:
      - "**.go"
      - "**.mod"
      - "**.sum"
  push:
    branches: ["*"]
    paths:
      - "**.go"
      - "**.mod"
      - "**.sum"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  go-test:
    uses: esacteksab/.github/.github/workflows/go-test.yml@848feff4f2e6fa028d7f3dae9193dcc1129a16e5  # v0.87.9
